apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: hello-world
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - hello-world.dataiku.idhub.io
      secretName: hello-world-cert

  rules:
    - host: hello-world.dataiku.idhub.io
      http:
        paths:
          - backend:
              serviceName: hello-world
              servicePort: 5050
              