apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: keycloak
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-keycloak"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - keycloak.platform.dkucloud-dev.com
      secretName: letsencrypt-keycloak

  rules:
    - host: keycloak.platform.dkucloud-dev.com
      http:
        paths:
          - pathType: ImplementationSpecific 
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
              