apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      nodeSelector:
        pool-name: default-pool
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          ports:
            - name: http-server
              containerPort: 5432
          volumeMounts:
            - name: db-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
          env:
            - name: GCLOUD_PROJECT_ID
              value: dataiku-dev
            - name: DATABASE_ID
              value: keycloak
          command: ["/cloud_sql_proxy"]
          args: ["-instances=$(GCLOUD_PROJECT_ID):europe-west2:$(DATABASE_ID)=tcp:0.0.0.0:5432",
                 "-credential_file=/secrets/cloudsql/credentials.json",
                 "-term_timeout=10s"]
        - name: keycloak
          image: quay.io/keycloak/keycloak:16.1.1
          imagePullPolicy: Always
          ports:
            - name: http-server
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
          resources:
            requests:
              memory: "600Mi"
              cpu: "300m"
            limits:
              memory: "1000Mi"
          env:
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: DB_VENDOR
              value: "POSTGRES"
            - name: DB_PORT
              value: "5432"
            - name: DB_ADDR
              value: "127.0.0.1"
            - name: DB_DATABASE
              value: "keycloak"
            - name: HOSTNAME
              value: keycloak.dataiku.idhub.io
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_SCHEMA
              value: "public"
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: password
      volumes:
        - name: db-credentials
          secret:
            secretName: db-credentials
            items:
              - key: sqlproxy-service-account
                path: credentials.json

             