namespace: keycloak
resources:
  - namespace.yml
  - letsencrypt-staging-issuer.yml
  - letsencrypt-keycloak-issuer.yml
  - keycloak.deployment.yml
  - keycloak.service.yml
  - ingress.yml
  - hello-world.deployment.yml
  - hello-world.ingress.yml
  - hello-world.service.yml
  - fm.ingress.yml
  - fm.service.yml
  - fm.endpointslice.yml

generators:
  - secret-generator.yml