apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  selector:
    matchLabels:
      app: ldap
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: ldap
          image: docker.io/bitnami/openldap:latest
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ROOT
              value: dc=platform,dc=dkucloud-dev,dc=com
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_CUSTOM_LDIF_DIR
              value: /ldap-config/
            - name: BITNAMI_DEBUG
              value: "true"
            - name: LDAP_LOGLEVEL
              value: "4"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: openldap
          ports:
            - name: tcp-ldap
              containerPort: 1389
            - name: tls-ldap
              containerPort: 1636
          volumeMounts:
            - mountPath: /ldap-config/
              name: ldap-config
      volumes:
        - name: ldap-config
          configMap:
            name: ldap-configmap