apiVersion: v1
kind: Secret
metadata:
    name: openldap
    namespace: keycloak
type: Opaque
data:
    adminpassword: ENC[AES256_GCM,data:rmmb96NUpRnpZ+UzK1YiVQ==,iv:1fPq9FT+Cdo3Nkpwsp631pfPmyvvDnjl/cWWdnvsg54=,tag:KIxYX7yzV7zaXaRGNTqXvA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dataiku-dev/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-01-30T10:17:38Z"
          enc: CiQAKJspku/30SLhbD7OsacrNh30yd8jT3zRoxhHhem+L07IPtsSSQArKxJwfQ9KDV/OwZOwyqMW7Rj7ZVnmCFH3HnU1/Wnsvk76BsAeyPAVwqWK4uGHxsiqGciE4f/l6BvuhTnljvRv54ve2d4QMF8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-30T10:17:38Z"
    mac: ENC[AES256_GCM,data:e7FkziqmEMYg1GB5V1RQMxRwMLXWYUyTS219+2eidN6GWtfoWlJoL154NsMVavi1Mp+n0vPyP0FC++mmRHKMesHGfhguRtenQChlNN6zOuE/gE90q7apujGJXfqIN+WM5PKhlFA2EfBwRXpsOvmjEIGe8cN1YKaK03R11GlQSz8=,iv:YZCX0WSJNdjIITS8Abr1iYz5hl/7vzW8rkQH398HgJg=,tag:gTVCymBL61vClTRq44zjKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
